baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Khataei"
    author = "Javad"
    description = "Javad"
    

    [params.theme]
        allowToggle = true
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        altTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Javad Khataei"
		tagline = "Data Scientist at Beap Lab"
		location = "Canada"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/khataei/"
            title = "LinkedIn"		
      #  [[params.social.list]]
       #     class = "fab"
        #    icon = "fa-stack-overflow"
         #   url = "#"
          #  title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/javad-mun"
            title = "GitHub"
 #       [[params.social.list]]
  #          class = "fab"
   #         icon = "fa-twitter"
    #        url = "#"
     #       title = "Twitter"
	#	[[params.social.list]]
     ###     url = "#"
         #   title = "Google Scholar"
		#[[params.social.list]]
          #  class = "ai"
           # icon = "ai-researchgate"
            #url = "#"
            #title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"

   # [[params.showInAccordion]]
    #    item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I have a master’s degree in computer science from *Memorial University*. At the *BEAP lab*, I enjoy working with data and applying machine learning algorithms to it. **R** and **Python** are my favourite languages, and I like developing packages to help other R users too."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = " Junior Data Scientist"
            dates = "Apr 2019 - *Present*"
            link = "http://www.beaplab.com/home/team/"
            company = "Beap Lab"
            detail1 = " * Processes, prepares and cleans wearable sensors’ data for further statistical analysis with Python or R."
            detail2 = " * Develops detection and classification algorithms using machine learning and signal processing tools."
            detail3 = " * Creates and maintains R packages to produce reusable codes."
            detail4 = " * Assists lab members with their data analysis, machine learning and data mining questions."


        [[params.experience.list]]
            position = "Junior Android Developer"
            dates = "Apr 2017 - Aug 2017"
            link = "http://www.netray.ir"
            company = "Netray"
            detail1 = " *  Developed Android applications, and gained experience in Java, SQL, and Python."
            detail2 = " * Assisted the development team in improving code quality through testing and code reviews."

        [[params.experience.list]]
            position = "Data Analyst"
            dates = "Apr 2015 - Feb 2017"
            link = "http://www.sealandws.com"
            company = "SeaLand well services"
            detail1 = " *  Processed and analyzed drilling data and presented KPIs."
            detail2 = " * Supervised drilling rig crews and monitored their performance."

        [[params.experience.list]]
            position = "Computer Technician"
            dates = "Apr 2013 - Feb 2015"
            link = "http://www.en.sharif.edu/"
            company = "Sharif University of Technology"  
            detail1 = " *  Provided the network users with technical computer consultation."
            detail2 = " * Installed and upgraded software and hardware to maintain network."


    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "M.S. in Computer Science"
            college = "Memorial University of Newfoundland"
            dates = "2017 - 2019"
            uni_city = "St. John's, NL"
           # thesis_title = ""
            #thesis_link = "#"
        [[params.education.list]]
            degree = "M.S. in Reservoir Engineering"
            college = "University of Tehran"
            dates = "2010 - 2012"
            #thesis_title = "Effect of humans on other humans: a study of human behavior."
            #thesis_link = "#"
        [[params.education.list]]
            degree = "B.S. in Petroleum Engineering"
            college = "Sharif University of Technology"
            dates = "2005 - 2010"


    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "R, Tidyverse"
            skillrating = 85
        [[params.skill.list]]
            skill = "Python, Numpy, Pandas"
            skillrating = 70
        [[params.skill.list]]
            skill = "Java, Keras, SQL"
            skillrating = 65
        [[params.skill.list]]
            skill = "Machine Learning"
            skillrating = 80
        [[params.skill.list]]
            skill = "Data Cleaning"
            skillrating = 90

    # Publication section
    [params.publication]
        title = "Certification"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["title", "authors", "date"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Coursera"]

        [[params.publication.list]]
            title = " - Python data structures"
            authors = "By University of Michigan"
            date = "Jan 2018"
            journal = ""
            link = "https://www.coursera.org/account/accomplishments/certificate/8USA24Y43HJ3?utm_medium=certificate&utm_source=link&utm_campaign=copybutton_certificate"
            type = "Coursera"

        [[params.publication.list]]
            title = " - Introduction to Structured Query Language (SQL)"
            authors = "By University of Michigan"
            date = "Jan 2018"
            journal = ""
            link = "https://www.coursera.org/account/accomplishments/certificate/5MN8SU4DRZQ5?utm_medium=certificate&utm_source=link&utm_campaign=copybutton_certificate"
            type = "Coursera"

        [[params.publication.list]]
            title = " - Getting Started with Python"
            authors = "By University of Michigan"
            date = "Jan 2018"
            journal = ""
            link = "https://www.coursera.org/account/accomplishments/certificate/N6DUA8FFN5GS?utm_medium=certificate&utm_source=link&utm_campaign=copybutton_certificate"
            type = "Coursera"



    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "ActivityCounts Package"
            url = "https://cran.r-project.org/web/packages/activityCounts/index.html"
            description = "An R package to calculate Actilife activity counts, available on CRAN                             "
        [[params.project.list]]
            title = "Beap Package"
            url = "https://github.com/Javad-mun/Beap"
            description = " An R package for modeling and classifying physical activity"
        [[params.project.list]]
            title = "DYNOBAL"
            url = "https://github.com/Javad-mun/DYNOBAL"
            description = "Software to estimate underground oil reservoir volume written in C#"         


    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Hiking"
        [[params.hobby.list]]		
		    hobby = "Baking"